language: php
php:
  - '8.0'
services: docker
install:
  - composer install
  - docker-compose up -d
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --env=test
script:
  - ./vendor/bin/simple-phpunit