language: php
php:
  - '8.0'
services:
  - docker
before_install:
  - docker-compose up -d
install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
script:
  - ./vendor/bin/simple-phpunit